default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123
  #this password will be used for all environments, as it is defined on default, you don't need to define again

development:
  <<: *default
  database: Final_Capstone_Backend

test:
  <<: *default
  database: Final_Capstone_Backend_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
